/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#2a1700",
        "inverse-surface": "#2a322a",
        "on-tertiary-fixed-variant": "#653e00",
        "on-error-container": "#93000a",
        "primary-container": "#22c55e",
        "secondary-fixed": "#d8e2ff",
        "tertiary-container": "#ef9900",
        "surface-container-low": "#edf6ea",
        "secondary-fixed-dim": "#adc6ff",
        "primary-fixed-dim": "#4ae176",
        "surface-container": "#e8f0e4",
        "tertiary": "#855300",
        "surface-dim": "#d4ddd0",
        "tertiary-fixed": "#ffddb8",
        "on-background": "#161d16",
        "on-primary-container": "#004b1e",
        "surface-tint": "#006e2f",
        "primary-fixed": "#6bff8f",
        "on-surface-variant": "#3d4a3d",
        "error": "#ba1a1a",
        "on-tertiary-container": "#5c3800",
        "outline": "#6d7b6c",
        "on-primary-fixed": "#002109",
        "surface-container-highest": "#dce5d9",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#001a42",
        "on-secondary-container": "#fefcff",
        "outline-variant": "#bccbb9",
        "surface": "#f3fcef",
        "inverse-on-surface": "#ebf3e7",
        "on-primary-fixed-variant": "#005321",
        "tertiary-fixed-dim": "#ffb95f",
        "background": "#f3fcef",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#004395",
        "surface-container-high": "#e2ebde",
        "on-secondary": "#ffffff",
        "on-surface": "#161d16",
        "inverse-primary": "#4ae176",
        "primary": "#006e2f",
        "surface-variant": "#dce5d9",
        "on-primary": "#ffffff",
        "surface-bright": "#f3fcef",
        "secondary-container": "#2170e4",
        "secondary": "#0058be"
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "sm": "0.25rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "base": "4px",
        "xs": "4px",
        "sm": "8px",
        "md": "16px",
        "lg": "24px",
        "xl": "40px",
        "2xl": "64px",
        "gutter": "24px",
        "margin-mobile": "16px",
        "margin-desktop": "48px"
      },
      fontFamily: {
        "display": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "label-sm": ["Geist", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "mono": ["Geist", "monospace"]
      }
    },
  },
  plugins: [],
}
